// Thin wrapper around the Airtable REST API (server-only: uses secret env vars).
// Table/field names match the LIVE "Safeserve App" base (checked against the schema).
// Linked-record fields (Task, Completed By, Reported By, Assigned To, Logged By,
// Generated By) must be written as arrays of record IDs, e.g. ["recXXXX"].
//
// PIN storage uses "PIN Hash" (not the old locked "PIN" field).

import {
  CHECKLIST_STATUS,
  ISSUE_STATUS,
  LOG_STATUS,
  OVERALL_STATUS,
  REPORT_THRESHOLDS,
  earliestWindowStart,
  todayISO,
  windowStart,
} from "@/lib/schema";

const BASE_URL = `https://api.airtable.com/v0/${process.env.AIRTABLE_BASE_ID}`;

export const TABLES = {
  USERS: "Users",
  CHECKLISTS: "Checklists",
  COMPLIANCE_LOGS: "Compliance Logs",
  ISSUES_LOG: "Issues Log",
  TEMP_LOGS: "Temperature Logs",
  INSPECTION_REPORTS: "Inspection Report", // singular in the live base
  STAFF_CERTS: "Staff Certification Table", // live table name
};

// ---- helpers -------------------------------------------------------------

async function airtableRequest(path, options = {}) {
  const res = await fetch(`${BASE_URL}/${path}`, {
    ...options,
    cache: "no-store",
    headers: {
      Authorization: `Bearer ${process.env.AIRTABLE_API_KEY}`,
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Airtable request failed (${res.status}): ${body}`);
  }
  return res.json();
}

// Escape a value for use inside a double-quoted Airtable formula string.
const esc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const trim = (v) => (typeof v === "string" ? v.trim() : v);
const first = (arr) => (Array.isArray(arr) ? arr[0] : undefined);

async function listRecords(table, { formula, sort = [], max = 500 } = {}) {
  const out = [];
  let offset;
  do {
    const params = new URLSearchParams({ pageSize: "100" });
    if (formula) params.set("filterByFormula", formula);
    sort.forEach((s, i) => {
      params.set(`sort[${i}][field]`, s.field);
      params.set(`sort[${i}][direction]`, s.direction || "asc");
    });
    if (offset) params.set("offset", offset);
    const data = await airtableRequest(`${encodeURIComponent(table)}?${params}`);
    out.push(...data.records);
    offset = data.offset;
  } while (offset && out.length < max);
  return out.slice(0, max);
}

const scoped = (restaurantName) => `{Restaurant Name} = "${esc(restaurantName)}"`;

async function createRecord(table, fields) {
  return airtableRequest(encodeURIComponent(table), {
    method: "POST",
    body: JSON.stringify({ fields }),
  });
}

async function patchRecord(table, id, fields) {
  return airtableRequest(`${encodeURIComponent(table)}/${id}`, {
    method: "PATCH",
    body: JSON.stringify({ fields }),
  });
}

async function getRecord(table, id) {
  return airtableRequest(`${encodeURIComponent(table)}/${id}`);
}

// ---- Users / auth ---------------------------------------------------------

export async function findUserByEmail(email) {
  const formula = encodeURIComponent(
    `AND(LOWER({Email}) = "${esc(String(email).toLowerCase())}", {active} = TRUE())`
  );
  const data = await airtableRequest(
    `${TABLES.USERS}?filterByFormula=${formula}&maxRecords=1`
  );
  if (!data.records || data.records.length === 0) return null;

  const record = data.records[0];
  return {
    id: record.id,
    name: record.fields["Name"],
    email: record.fields["Email"],
    pinHash: record.fields["PIN Hash"],
    role: trim(record.fields["Role"]), // "Owner" | "Manager" | "Staff"
    restaurantName: record.fields["Restaurant Name"],
  };
}

// Fresh lookup by record ID, used to re-validate a session on every API call.
export async function getUserById(id) {
  try {
    const rec = await getRecord(TABLES.USERS, id);
    return {
      id: rec.id,
      name: rec.fields["Name"],
      role: trim(rec.fields["Role"]),
      restaurantName: rec.fields["Restaurant Name"],
      active: !!rec.fields["active"],
    };
  } catch (err) {
    if (String(err.message).includes("(404)")) return null;
    throw err;
  }
}

export async function setUserPinHash(recordId, pinHash) {
  await patchRecord(TABLES.USERS, recordId, { "PIN Hash": pinHash });
}

// Active users of one restaurant (used to turn linked record IDs into names).
export async function getRestaurantUsers(restaurantName) {
  const records = await listRecords(TABLES.USERS, { formula: scoped(restaurantName) });
  return records.map((r) => ({
    id: r.id,
    name: r.fields["Name"],
    role: trim(r.fields["Role"]),
    active: !!r.fields["active"],
  }));
}

function nameLookup(users) {
  const map = new Map(users.map((u) => [u.id, u.name]));
  return (id) => (id ? map.get(id) ?? "Unknown" : "");
}

// ---- Checklists -------------------------------------------------------------
// Task templates are shared by every restaurant. Whether a task is DONE is worked
// out per restaurant from Compliance Logs (inside the task's current window), not
// from the shared Checklists.Status field, which can't tell restaurants or days apart.

// Map of taskId -> latest completion time (ms) for this restaurant since `since`.
async function completionsSince(restaurantName, since) {
  const iso = new Date(since.getTime() - 60 * 1000).toISOString(); // inclusive of `since`
  const formula = `AND(${scoped(restaurantName)}, IS_AFTER({Date Completed}, "${iso}"))`;
  const logs = await listRecords(TABLES.COMPLIANCE_LOGS, { formula, max: 3000 });
  const latest = new Map();
  for (const r of logs) {
    if (trim(r.fields["Status"]) !== LOG_STATUS.COMPLETED.trim()) continue;
    const when = new Date(r.fields["Date Completed"]).getTime();
    for (const taskId of r.fields["Task"] || []) {
      if (!latest.has(taskId) || latest.get(taskId) < when) latest.set(taskId, when);
    }
  }
  return latest;
}

export async function getChecklists(restaurantName) {
  const now = new Date();
  const [records, latest] = await Promise.all([
    listRecords(TABLES.CHECKLISTS),
    completionsSince(restaurantName, earliestWindowStart(now)),
  ]);
  return records.map((r) => {
    const done =
      latest.has(r.id) && latest.get(r.id) >= windowStart(r.fields["Frequency"], now).getTime();
    return {
      id: r.id,
      taskName: r.fields["Task Name"],
      section: r.fields["Section"],
      frequency: trim(r.fields["Frequency"]),
      area: r.fields["Area"],
      critical: r.fields["Critical"],
      fdaReference: r.fields["FDA Reference "], // trailing space in the live field name
      status: done ? CHECKLIST_STATUS.COMPLETED : "Pending",
    };
  });
}

// Writes the audit record FIRST, then flips the legacy status, so the audit trail
// can never be missing a task the UI shows as done. Returns:
//   { notFound: true }       task id doesn't exist
//   { alreadyDone: true }    already completed in the current window (no duplicate log)
//   { ok: true }
export async function markTaskComplete({ taskId, completedByRecordId, restaurantName }) {
  let task;
  try {
    task = await getRecord(TABLES.CHECKLISTS, taskId);
  } catch (err) {
    if (/\((404|422)\)/.test(String(err.message))) return { notFound: true };
    throw err;
  }

  const since = windowStart(task.fields["Frequency"]);
  const latest = await completionsSince(restaurantName, since);
  if (latest.has(taskId) && latest.get(taskId) >= since.getTime()) return { alreadyDone: true };

  await createRecord(TABLES.COMPLIANCE_LOGS, {
    Task: [taskId],
    "Completed By": [completedByRecordId],
    "Date Completed": new Date().toISOString(),
    Status: LOG_STATUS.COMPLETED,
    "Restaurant Name": restaurantName,
  });
  // Legacy: kept so any Make.com scenario that reads Checklists.Status keeps working.
  // The app itself no longer reads this field.
  await patchRecord(TABLES.CHECKLISTS, taskId, { Status: CHECKLIST_STATUS.COMPLETED });
  return { ok: true };
}

// ---- Compliance logs (read-only audit trail) ---------------------------------

export async function getComplianceLogs(restaurantName) {
  const [records, users] = await Promise.all([
    listRecords(TABLES.COMPLIANCE_LOGS, {
      formula: scoped(restaurantName),
      sort: [{ field: "Date Completed", direction: "desc" }],
      max: 300,
    }),
    getRestaurantUsers(restaurantName),
  ]);
  const nameOf = nameLookup(users);
  return records.map((r) => {
    const f = r.fields;
    const lookup = f["Lookup Tasks Name"];
    return {
      id: r.id,
      logId: f["Log ID"],
      taskName: Array.isArray(lookup) ? lookup.join(", ") : lookup || "",
      completedBy: nameOf(first(f["Completed By"])),
      dateCompleted: f["Date Completed"],
      status: trim(f["Status"]),
      notes: f["Notes"] || "",
      temperatureReading: f["Temperature Reading"],
    };
  });
}

// ---- Temperature logs ---------------------------------------------------------

function mapTempLog(r, nameOf) {
  const f = r.fields;
  return {
    id: r.id,
    logId: f["Log ID"],
    equipment: f["Equipment"],
    temperature: f["Temperature (°F)"],
    safeZone: f["Safe Zone"] || "",
    loggedBy: nameOf(first(f["Logged By"])),
    dateTime: f["Date & Time"],
    correctiveAction: f["Corrective Action Taken"] || "",
    notes: f["Notes"] || "",
  };
}

export async function getTempLogs(restaurantName) {
  const [records, users] = await Promise.all([
    listRecords(TABLES.TEMP_LOGS, {
      formula: scoped(restaurantName),
      sort: [{ field: "Date & Time", direction: "desc" }],
      max: 200,
    }),
    getRestaurantUsers(restaurantName),
  ]);
  const nameOf = nameLookup(users);
  return records.map((r) => mapTempLog(r, nameOf));
}

export async function createTempLog({ equipment, temperature, correctiveAction, notes, userId, userName, restaurantName }) {
  const fields = {
    Equipment: equipment,
    "Temperature (°F)": temperature,
    "Logged By": [userId],
    "Date & Time": new Date().toISOString(),
    "Restaurant Name": restaurantName,
  };
  if (correctiveAction) fields["Corrective Action Taken"] = correctiveAction;
  if (notes) fields["Notes"] = notes;
  const rec = await createRecord(TABLES.TEMP_LOGS, fields);
  return mapTempLog(rec, () => userName);
}

// ---- Issues log -----------------------------------------------------------------

function mapIssue(r, nameOf) {
  const f = r.fields;
  return {
    id: r.id,
    issueId: f["Issue ID"],
    issueType: f["Issue Type"],
    description: f["Description"] || "",
    area: f["Area"],
    severity: f["Severity"],
    status: trim(f["Status"]),
    reportedBy: nameOf(first(f["Reported By"])),
    dateReported: f["Date Reported"],
    assignedToId: first(f["Assigned To"]) || "",
    assignedTo: nameOf(first(f["Assigned To"])),
    dueDate: f["Due Date"] || "",
    resolutionNotes: f["Resolution Notes"] || "",
    dateResolved: f["Date Resolved"] || "",
  };
}

export async function getIssuesLog(restaurantName) {
  const [records, users] = await Promise.all([
    listRecords(TABLES.ISSUES_LOG, {
      formula: scoped(restaurantName),
      sort: [{ field: "Date Reported", direction: "desc" }],
      max: 300,
    }),
    getRestaurantUsers(restaurantName),
  ]);
  const nameOf = nameLookup(users);
  return {
    issues: records.map((r) => mapIssue(r, nameOf)),
    users: users.filter((u) => u.active).map((u) => ({ id: u.id, name: u.name })),
  };
}

export async function createIssue({ issueType, description, area, severity, userId, userName, restaurantName }) {
  const rec = await createRecord(TABLES.ISSUES_LOG, {
    "Issue Type": issueType,
    Description: description,
    Area: area,
    Severity: severity,
    "Reported By": [userId],
    "Date Reported": new Date().toISOString(),
    Status: ISSUE_STATUS.OPEN,
    "Restaurant Name": restaurantName,
  });
  return mapIssue(rec, () => userName);
}

// Returns null if the issue doesn't exist or belongs to another restaurant.
export async function getIssueForRestaurant(id, restaurantName) {
  try {
    const rec = await getRecord(TABLES.ISSUES_LOG, id);
    return rec.fields["Restaurant Name"] === restaurantName ? rec : null;
  } catch {
    return null;
  }
}

export async function updateIssue(id, { status, assignedToId, dueDate, resolutionNotes }) {
  const fields = {};
  if (status !== undefined) fields["Status"] = status;
  if (assignedToId !== undefined) fields["Assigned To"] = assignedToId ? [assignedToId] : [];
  if (dueDate !== undefined) fields["Due Date"] = dueDate || null;
  if (resolutionNotes !== undefined) fields["Resolution Notes"] = resolutionNotes;
  if (status === ISSUE_STATUS.RESOLVED) fields["Date Resolved"] = todayISO();
  if (status && status !== ISSUE_STATUS.RESOLVED) fields["Date Resolved"] = null;
  await patchRecord(TABLES.ISSUES_LOG, id, fields);
}

// ---- Staff certifications ------------------------------------------------------------

function mapCert(r) {
  const f = r.fields;
  return {
    id: r.id,
    staffMemberName: f["Staff Member Name"] || "",
    certificationType: f["Certification Type"],
    certificateNumber: f["Certificate Number"] || "",
    issueDate: f["Issue Date"] || "",
    expiryDate: f["Expiry Date"] || "",
    status: f["Status"] || "",
  };
}

export async function getStaffCertifications(restaurantName) {
  const records = await listRecords(TABLES.STAFF_CERTS, {
    formula: scoped(restaurantName),
    sort: [{ field: "Expiry Date", direction: "asc" }],
  });
  return records.map(mapCert);
}

export async function createStaffCertification({ staffMemberName, certificationType, certificateNumber, issueDate, expiryDate, restaurantName }) {
  const fields = {
    "Staff Member Name": staffMemberName,
    "Certification Type": certificationType,
    "Expiry Date": expiryDate,
    "Restaurant Name": restaurantName,
  };
  if (certificateNumber) fields["Certificate Number"] = certificateNumber;
  if (issueDate) fields["Issue Date"] = issueDate;
  return mapCert(await createRecord(TABLES.STAFF_CERTS, fields));
}

// ---- Inspection reports --------------------------------------------------------------------

// Live numbers used for the report snapshot.
//   Compliance score = % of checklist tasks currently marked Completed.
//   Critical issues  = unresolved issues with severity Critical or High.
export async function getInspectionSnapshot(restaurantName) {
  const [checklists, { issues }] = await Promise.all([getChecklists(restaurantName), getIssuesLog(restaurantName)]);
  const total = checklists.length;
  const done = checklists.filter((t) => t.status === CHECKLIST_STATUS.COMPLETED).length;
  const score = total ? Math.round((done / total) * 100) : 0;

  const unresolved = issues.filter((i) => i.status !== ISSUE_STATUS.RESOLVED.trim());
  const open = unresolved.length;
  const critical = unresolved.filter((i) => i.severity === "Critical" || i.severity === "High").length;

  let overall = OVERALL_STATUS.READY;
  if (critical > 0 || score < REPORT_THRESHOLDS.atRisk) overall = OVERALL_STATUS.AT_RISK;
  else if (open > 0 || score < REPORT_THRESHOLDS.ready) overall = OVERALL_STATUS.NEEDS_ATTENTION;

  return { score, tasksDone: done, tasksTotal: total, openIssues: open, criticalIssues: critical, overallStatus: overall };
}

function mapReport(r, nameOf) {
  const f = r.fields;
  return {
    id: r.id,
    reportId: f["Report ID"],
    reportDate: f["Report Date"] || "",
    inspectionType: trim(f["Inspection Type"]),
    complianceScore: f["Compliance Score (%)"],
    openIssues: f["Open Issues Count"],
    criticalIssues: f["Critical Issues Count"],
    overallStatus: trim(f["Overall Status"]),
    inspectorName: f["Inspector Name"] || "",
    inspectorNotes: f["Inspector Notes"] || "",
    actionPlan: f["Action Plan"] || "",
    generatedBy: nameOf(first(f["Generated By"])),
    pdfUrl: first(f["Report PDF"])?.url || "",
  };
}

export async function getInspectionReports(restaurantName) {
  const [records, users] = await Promise.all([
    listRecords(TABLES.INSPECTION_REPORTS, {
      formula: scoped(restaurantName),
      sort: [{ field: "Report Date", direction: "desc" }],
      max: 100,
    }),
    getRestaurantUsers(restaurantName),
  ]);
  const nameOf = nameLookup(users);
  return records.map((r) => mapReport(r, nameOf));
}

export async function createInspectionReport({ inspectionType, inspectorName, inspectorNotes, actionPlan, userId, userName, restaurantName }) {
  const snap = await getInspectionSnapshot(restaurantName);
  const fields = {
    "Report Date": todayISO(),
    "Restaurant Name": restaurantName,
    "Generated By": [userId],
    "Inspection Type": inspectionType,
    "Compliance Score (%)": snap.score,
    "Open Issues Count": snap.openIssues,
    "Critical Issues Count": snap.criticalIssues,
    "Overall Status": snap.overallStatus,
  };
  if (inspectorName) fields["Inspector Name"] = inspectorName;
  if (inspectorNotes) fields["Inspector Notes"] = inspectorNotes;
  if (actionPlan) fields["Action Plan"] = actionPlan;
  const rec = await createRecord(TABLES.INSPECTION_REPORTS, fields);
  return mapReport(rec, () => userName);
}
